version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"  # Опционально, для веб-интерфейса
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - my-network


  logistics:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_CONNECTION_STRING: amqp://guest:guest@rabbitmq:5672/
    container_name: "logistics"
    networks:
      - my-network

networks:
   my-network:
